packages:
  - studio

allowBuilds:
  esbuild: true
overrides:
  js-yaml: 4.3.1
  smol-toml: 1.6.1
  uuid: 11.1.1
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.10.4'
  - '@astrojs/markdown-satteri@0.3.7'
  - '@astrojs/react@6.0.4'
  - astro@7.2.4
